; ESP8266 D1 mini Leslie speed controller
; MIDI IN on D1 (GPIO5), 31250 baud.
; D4 = switch pulse out, D5 = speed indicator in (high=fast, low=slow)

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
build_src_filter = +<*> -<find_led/>
